services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static:ro
      - ./media:/mediafiles:ro
    depends_on:
      - web
    networks:
      mynetworklabtest:
        ipv6_address: 2a01:d0:a6c9:3161::2

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./custom_postgres:/etc/postgresql/conf.d
    command: >
      -c config_file=/etc/postgresql/conf.d/postgresql.conf
    networks:
      mynetworklabtest:
        ipv6_address: 2a01:d0:a6c9:3161::3

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - static_volume:/static:ro
      - media_volume:/media:ro
    networks:
      mynetworklabtest:
        ipv6_address: 2a01:d0:a6c9:3161::4

volumes:
  static_volume:
  media_volume:

networks:
  mynetworklabtest:
    driver: bridge
    enable_ipv6: true

    driver_opts:
      com.docker.network.bridge.name: myipv6bridge
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.enable_ipv4: "false"
      # IMPORTANT! Disable IPv6 NAT (NAT66)
      com.docker.network.bridge.gateway_mode_ipv6: 'routed'
    ipam:
      driver: default
      config: 
        - subnet: 1111:2222:3333:4444::/64
          gateway: 1111:2222:3333:4444::1